global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'elixir-app'
    static_configs:
      - targets: [time-manager-hyogo.gigalixirapp.com]

  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
